runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  expiration: "100d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: "default-src 'none'; img-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "100d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: "default-src 'none'; report-uri: https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  expiration: "100d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: "default-src 'none'; report-uri: https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer

- url: /humans\.txt
  static_files: humans.txt
  upload: humans\.txt
  expiration: "100d"
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Content-Security-Policy: "default-src 'none'; report-uri: https://markridgwell.report-uri.com/r/d/csp/enforce"
    Expect-CT: max-age=0, report-uri="https://markridgwell.report-uri.com/r/d/ct/reportOnly"
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block; report=https://markridgwell.report-uri.com/r/d/xss/enforce
    X-Content-Type-Options: nosniff
    strict-transport-security: max-age=31536000; includeSubdomains; preload
    Referrer-Policy: no-referrer

- url: /tasks/sync
  script: tasksync.app
  login: admin
  secure: optional

- url: /sitemap
  script: sitemap.app
  secure: always
  redirect_http_response_code: 301

- url: .*
  script: main.app
  secure: always
  redirect_http_response_code: 301

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?\.pyproj
- ^(.*/)?\.sln
- ^\.gitignore
- ^\.git/(.*/)?
- ^\.idea/(.*/)?
