application: livebandphotosuk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  expiration: "100d"

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  expiration: "100d"

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  expiration: "100d"

- url: /humans\.txt
  static_files: humans.txt
  upload: robots\.txt
  expiration: "100d"

- url: /tasks/sync
  script: tasksync.app
  login: admin
  secure: optional

- url: /sitemap
  script: sitemap.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?\.pyproj
- ^(.*/)?\.sln
- ^\.gitignore
- ^\.git/(.*/)?

pagespeed:
  domains_to_rewrite:
    - www.livebandphotos.com    
    - livebandphotosuk.appspot.com
  url_blacklist:
    - http://www.livebandphotos.com/sitemap
    - http://livebandphotosuk.appspot.com/sitemap
  enabled_rewriters:
    - ProxyCss
    - ProxyImages
    - ProxyJs
    - ConvertMetaTags
    - InlineCss
    - InlineJs
    - CollapseWhitespace
    - ElideAttributes
    - RemoveComments
    - RemoveQuotes
    - LeftTrimUrls
    - CombineCss
    - MoveCssToHead
    - MinifyCss
    - CombineJs
    - JsOptimize
  disabled_rewriters:
    - DeferJs
	- InlineImages
	- CombineHeads

