name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_only:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.SOURCE_PUSH_TOKEN }}
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8
      - uses: actions/cache@v2.1.7
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - run: echo "WHEN=$(date +"%Y-%m-%d")" >> "$GITHUB_ENV"
      - run: echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
      - name: Rebuild site
        run: python updater/extract.py
      - name: Deploy
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dst'
