name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_only:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.SOURCE_PUSH_TOKEN }}

      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8

      - uses: actions/cache@v3
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - run: echo "WHEN=$(date +"%Y-%m-%d")" >> "$GITHUB_ENV"

      - run: echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"

      - name: Rebuild site
        run: python updater/extract.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dst
          cname: livebandphotos.com
