name: Build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Deploy
      run: gcloud app deploy app.yaml --project ${{secrets.GCLOUD_PROJECT_ID}}