name: Update Gigs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        SOURCE_PUSH_TOKEN: ${{ secrets.SOURCE_PUSH_TOKEN }}
      run: |-
        python updater/download.py
    - name: Commit and push if gigs.xml changed
      run: |-
        git diff
        git config --global user.email "gig-bot@example.com"
        git config --global user.name "GIG-bot"
        git diff --quiet || (git add updater/gigs.xml.md && git commit -m "Updated Gigs")
        git push
